spring:
  data:
    mongodb:
      uri: mongodb+srv://captainsinha2003_db_user:XKZPb9WYzRHTYm5A@cluster0.glwuwxg.mongodb.net/?appName=Cluster0
      database: jouranldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /jouranl
